### ISSUE TITLE
github登录提示需要输入验证码，无法正常登录和使用

### ISSUE THREAD

**Issue by 289070112** [Hell0W0rld0/Github_Hunter_By_Golang#1]
> A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.
> 
> Device: colly
> Verification code: 123456
 
现在github登录提示需要输入验证码，这个怎么过？

工具很赞，轻！！谢谢！

**Comment by Hell0W0rld0** [comment]
只需要自己用网页登录下，然后以后就不用登录了。
